### ISSUE TITLE
Unable to install this sddon on hassio 

### ISSUE THREAD

**Issue by MiAutomations** [raph2i/hassio-addons#10]
Hello I'm facing this issue when i try to install this addon 

The command '/bin/ash -o pipefail -c apk add --no-cache python2 py2-paho-mqtt bash curl wget tar && curl -L https://raw.githubusercontent.com/MartyTremblay/sip2mqtt/master/sip2mqtt.py -o sip2mqtt.py && apk add --no-cache --virtual .build4pjsip alpine-sdk && apk add --no-cache libsrtp-dev python2-dev openssl-dev opus-dev && cd && wget -qnv "http://www.pjsip.org/release/2.7.2/pjproject-2.7.2.tar.bz2" -O - | tar xjf - && cd pjproject-2.7.2 && ./configure --with-external-srtp --enable-shared --disable-sound --disable-oss --disable-sdl --disable-speex-aec --disable-video --prefix=/usr/local > /dev/null && make dep && make && make install && cd pjsip-apps/src/python && make && make install && cd && rm -rf pjproject-2.7.2 && apk del .build4pjsip' returned a non-zero code: 1

![image](https://user-images.githubusercontent.com/47602733/103015476-66cb0b80-4538-11eb-9f72-bf30f8dccd0f.png)

Can anyone please help me in order to solve this issue ? Thank and bets regards

**Comment by nickrout** [comment]
You should probably try the commands manually one after the other.

**Comment by MiAutomations** [comment]
> You should probably try the commands manually one after the other.

Ok can you please explain, because I'm only try to execute the installation of the plugin over the Home Assistant interface ...

Thank you and best regards

**Comment by StuartJeffery** [comment]
I am getting the same error Hassio version 2020.12.7 Hass OS 5.9.

Any help would be great.

**Comment by MartyTremblay** [comment]
Looks like pjsip has removed version 2.7.2 and the URL is now a 404. Version 2.10 seems to be the latest...

I'm working on a fix along with other enhancements and I'll provide @raph2i a PR when done. No ETA at the moment since I'm juggling a few other things.
