### ISSUE TITLE
snapcast-server not starting up due to recent docker changes in HA

### ISSUE THREAD

**Issue by anshuman-d3** [raph2i/hassio-addons#18]
Snapcast-server version 0.25 is installed, but while starting up, getting the following error - `**"s6-overlay-suexec: fatal: can only run as pid 1"**`.

I did a little digging and found this page mentioning recent changes related to S6-Overlay -
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Please update the add-on to be compatible with this changes.

Environment Info -
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1
Device - Raspberry Pi 4B+

**Comment by dirething** [comment]
seeing the same in Home Assistant OS on a PC VM

**Comment by Bushbrand17** [comment]
Same problem here on raspberry pi 4 with the same specs and software versions as [anshuman-d3](https://github.com/anshuman-d3)

The same problem also exists with the librespot addon.

**Comment by fietstasss** [comment]
I'm also seeing this issue while using HA Core on a Virtualbox VM.
Would be great if this could be solved or worked around somehow, any hints?

**Comment by fietstasss** [comment]
Any update on how to get this working with HomeAssistant again?

**Comment by anshuman-d3** [comment]
this problem seems to be resolved, post the merger of PR by @fietstasss, however my snapserver is failing to start with the default config and throwing the following error -
`parse error: Expected string key before ':' at line 1, column 4`  (with the default config)
and
`Exception: invalid argument for --stream.buffer: 'null'`

![image](https://user-images.githubusercontent.com/6525959/184718388-189fa71a-afd3-4bcb-b566-1f18c8927ffd.png)

**Comment by imbahzor** [comment]
> this problem seems to be resolved, post the merger of PR by @fietstasss, however my snapserver is failing to start with the default config and throwing the following error - `parse error: Expected string key before ':' at line 1, column 4` (with the default config) and `Exception: invalid argument for --stream.buffer: 'null'`
> 
> ![image](https://user-images.githubusercontent.com/6525959/184718388-189fa71a-afd3-4bcb-b566-1f18c8927ffd.png)

I get the same issue, did anyone manage to solve this?

**Comment by LiveBootleg** [comment]
> > this problem seems to be resolved, post the merger of PR by @fietstasss, however my snapserver is failing to start with the default config and throwing the following error - `parse error: Expected string key before ':' at line 1, column 4` (with the default config) and `Exception: invalid argument for --stream.buffer: 'null'`
> > ![image](https://user-images.githubusercontent.com/6525959/184718388-189fa71a-afd3-4bcb-b566-1f18c8927ffd.png)
> 
> I get the same issue, did anyone manage to solve this?

Also getting the same on my side. Has anyone been able to resolve as yet?

**Comment by litinoveweedle** [comment]
Ok, have same issue as above. I modified run.sh to log on the fly created /etc/snapserver.conf and it is completely empty:

```
[stream]
stream = null
buffer = null
codec = null
send_to_muted = null
sampleformat = null
[http]
enabled = null
doc_root = null
[tcp]
enabled = null
[logging]
debug = null
[server]
threads = null
[server]
datadir = null

```

So it seems the issue is in [bashio::config](https://github.com/hassio-addons/bashio) parsing inside of the run.sh

**Comment by Art-Ev** [comment]
Hi !

I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)

My latest version is available with this PR : https://github.com/raph2i/hassio-addons/pull/22 (@raph2i)

If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver

**Comment by Art-Ev** [comment]
> Hi !
> 
> I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> 
> My latest version is available with this PR : #22 (@raph2i)
> 
> If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver

Have made some changes, seems to be working now. At least for me.

**Comment by imbahzor** [comment]
> > Hi !
> > I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> > My latest version is available with this PR : #22 (@raph2i)
> > If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver
> 
> Have made some changes, seems to be working now. At least for me.

Tried to install from your repo, but it just crashes the whole system without installing it for me.

**Comment by Art-Ev** [comment]
> > > Hi !
> > > I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> > > My latest version is available with this PR : #22 (@raph2i)
> > > If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver
> > 
> > 
> > Have made some changes, seems to be working now. At least for me.
> 
> Tried to install from your repo, but it just crashes the whole system without installing it for me.

What do you mean by "crash" ? On my installation, addon installation is very long (several minutes due to docker configuration, to be able to use Librespot) but after that it's running great. I'm running HA on a x64-x86 server, are you using a raspberry pi ?

Can you install the official "Spotify Connect" addon without crashing ? (my modifications are largely inspired by it)

**Comment by anshuman-d3** [comment]
> > Hi !
> > I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> > My latest version is available with this PR : #22 (@raph2i)
> > If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver
> 
> Have made some changes, seems to be working now. At least for me.

Thanks to your repo, it is working for me now. but yeah, installation takes a lot of time.

**Comment by imbahzor** [comment]
> > > > Hi !
> > > > I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> > > > My latest version is available with this PR : #22 (@raph2i)
> > > > If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver
> > > 
> > > 
> > > Have made some changes, seems to be working now. At least for me.
> > 
> > 
> > Tried to install from your repo, but it just crashes the whole system without installing it for me.
> 
> What do you mean by "crash" ? On my installation, addon installation is very long (several minutes due to docker configuration, to be able to use Librespot) but after that it's running great. I'm running HA on a x64-x86 server, are you using a raspberry pi ?
> 
> Can you install the official "Spotify Connect" addon without crashing ? (my modifications are largely inspired by it)

Yeah other add ons work fine to install, but for some reason when installing this one it just stands still for 30 minutes, reboots and with nothing installed after, will do another test this weekend

**Comment by kayo79** [comment]
> Hi !
> 
> I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> 
> My latest version is available with this PR : #22 (@raph2i)
> 
> If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver

Thank you for your work. Works perfect. I have tested successfully with Spotify Connect and mpd. I have managed to either run mpd or Spotify connect( librespot). How do I have to modify the source to use more than one stream so thah I can switch streams?

**Comment by rwjack** [comment]
```
The command '/bin/ash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 cargo=1.60.0-r2 git=2.36.3-r0 protobuf-dev=3.18.1-r3 pulseaudio-dev=15.0-r2 && apk add --no-cache pulseaudio=15.0-r2 && cargo install --locked --no-default-features --features pulseaudio-backend --root /usr --bin librespot --version 0.4.2 --verbose -- librespot && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/* ~/.cargo /usr/.crates.toml /usr/.crates2.json' returned a non-zero code: 2
```
@Art-Ev Building fails for me, any ideas?

**Comment by Art-Ev** [comment]
> > Hi !
> > I did some testing and got a "running" version but... I'm new to HA and new to Snapcast so I don't know if my remaining issues are related to the addon or to a bad network/SnapServer setup. (http://homeassistant.local:1780/ is accesible and I can connect with SnapDotNet and snapcast android app but cannot use SpotifyConnect through Librespot)
> > My latest version is available with this PR : #22 (@raph2i)
> > If anyone who had a working setup before can confirm what works and what doesn't .... You can install SnapServer addon using my working repo : https://github.com/Art-Ev/addon-snapserver
> 
> Thank you for your work. Works perfect. I have tested successfully with Spotify Connect and mpd. I have managed to either run mpd or Spotify connect( librespot). How do I have to modify the source to use more than one stream so thah I can switch streams?

You can use advanced options (hide by default) to add a 2nd and 3rd stream (only 3 available now but seems to be ok with majority of use cases)

**Comment by Art-Ev** [comment]
> ```
> The command '/bin/ash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 cargo=1.60.0-r2 git=2.36.3-r0 protobuf-dev=3.18.1-r3 pulseaudio-dev=15.0-r2 && apk add --no-cache pulseaudio=15.0-r2 && cargo install --locked --no-default-features --features pulseaudio-backend --root /usr --bin librespot --version 0.4.2 --verbose -- librespot && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/* ~/.cargo /usr/.crates.toml /usr/.crates2.json' returned a non-zero code: 2
> ```
> 
> @Art-Ev Building fails for me, any ideas?

Don't know... will check when I have some time but I can uninstall/reinstall with last HA updates without problem...

**Comment by rwjack** [comment]
The initial fix for me was to remove the git version dependency and use latest in the Dockerfile.

I made a fork: https://github.com/rwjack/addon-snapserver-spotify/

**Comment by BunpGhost** [comment]
> The initial fix for me was to remove the git version dependency and use latest in the Dockerfile.
> 
> I made a fork: https://github.com/rwjack/addon-snapserver-spotify/

Hi rwjack.
is it possible to use your addon with a stream from shairport for airplay?
If so, can you teel me how?

**Comment by rwjack** [comment]
@BunpGhost No unfortunately, though I did see this fork that was using it: https://github.com/gh7531/addon-snapserver

Unsure if it's working though

**Comment by BunpGhost** [comment]
> @BunpGhost No unfortunately, though I did see this fork that was using it: https://github.com/gh7531/addon-snapserver
> 
> Unsure if it's working though

it is not, it gives me this when installing:
`The command '/bin/ash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 cargo=1.60.0-r2 git=2.36.3-r0 protobuf-dev=3.18.1-r3 pulseaudio-dev=15.0-r2 shairport-sync && apk add --no-cache pulseaudio=15.0-r2 && cargo install --locked --no-default-features --features pulseaudio-backend --root /usr --bin librespot --version 0.4.2 --verbose -- librespot && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/* ~/.cargo /usr/.crates.toml /usr/.crates2.json' returned a non-zero code: 3`

I don't know how to fix it.. :( 
Thanks anyway

**Comment by rwjack** [comment]
I installed docker on my PC and tried building the image, that way you can have clear logging of what's going wrong
